"""Fetch EC2 On-Demand hourly USD rates from AWS public meteredUnitMaps (same feed as aws.amazon.com pricing).

Run from repo root: python scripts/refresh_ec2_public_prices.py

Writes ec2_ondemand_public.py (no third-party deps). Requires outbound HTTPS.

Not imported by the Streamlit app — offline maintainer workflow only. Deployed FinOps instances must not
execute this script from the serving tier; refresh bundles on a build/ops host, then redeploy artifacts.
"""
from __future__ import annotations

import gzip
import json
import sys
from collections import defaultdict
from pathlib import Path
from urllib.request import Request, urlopen

BASE = 'https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/ec2-ondemand-without-sec-sel'

# pricing_engine.SUPPORTED_REGIONS ids -> label in AWS JSON
REGION_LABELS: dict[str, str] = {
    'eu-west-1': 'EU (Ireland)',
    'us-east-1': 'US East (N. Virginia)',
    'ap-south-1': 'Asia Pacific (Mumbai)',
    'eu-central-1': 'EU (Frankfurt)',
}

OS_SEGMENTS: dict[str, str] = {
    'linux': 'Linux',
    'windows': 'Windows',
    'rhel': 'RHEL',
    'suse': 'SUSE',
}


def _fetch_json(url: str) -> dict:
    req = Request(url, headers={'User-Agent': 'finops-tool-refresh/1.0', 'Accept-Encoding': 'gzip, deflate'})
    with urlopen(req, timeout=180) as resp:
        raw = resp.read()
    if raw[:2] == b'\x1f\x8b':
        raw = gzip.decompress(raw)
    return json.loads(raw.decode('utf-8'))


def _parse_region_os(data: dict, aws_region_label: str) -> dict[str, float]:
    regs = data.get('regions') or {}
    block = regs.get(aws_region_label) or {}
    out: dict[str, float] = {}
    conflicts: list[tuple[str, float, float]] = []
    for _k, row in block.items():
        inst = (row.get('Instance Type') or '').strip().lower()
        if not inst:
            continue
        price_s = row.get('price')
        try:
            price = float(price_s)
        except (TypeError, ValueError):
            continue
        if inst in out:
            if abs(out[inst] - price) > 1e-09:
                conflicts.append((inst, out[inst], price))
            out[inst] = min(out[inst], price)
        else:
            out[inst] = price
    if conflicts:
        print('WARN: price conflicts (using min):', conflicts[:5], file=sys.stderr)
    return {k: round(v, 6) for k, v in sorted(out.items())}


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out_path = root / 'ec2_ondemand_public.py'

    nested: dict[str, dict[str, dict[str, float]]] = defaultdict(lambda: defaultdict(dict))
    manifest_dates: list[str] = []

    for rid, aws_label in REGION_LABELS.items():
        for os_key, seg in OS_SEGMENTS.items():
            url = f'{BASE}/{aws_label.replace(" ", "%20")}/{seg}/index.json'
            print('fetch', rid, os_key, '...', flush=True)
            data = _fetch_json(url)
            m = (data.get('manifest') or {}).get('hawkFilePublicationDate') or ''
            if m:
                manifest_dates.append(m)
            table = _parse_region_os(data, aws_label)
            nested[rid][os_key] = table
            print(' ', len(table), 'instance types', flush=True)

    as_of = max(manifest_dates) if manifest_dates else 'unknown'

    py_obj = {r: {o: nested[r][o] for o in OS_SEGMENTS} for r in REGION_LABELS}
    text = (
        '"""Auto-generated by scripts/refresh_ec2_public_prices.py — AWS EC2 On-Demand (meteredUnitMaps).\n'
        'Linux / Windows / RHEL / SUSE are separate SKUs (no flat surcharge approximation)."""\n'
        'from __future__ import annotations\n\n'
        f'EC2_ONDEMAND_PUBLIC_AS_OF: str = {as_of!r}\n\n'
        'EC2_ONDEMAND_BY_REGION_OS: dict[str, dict[str, dict[str, float]]] = '
        + repr(py_obj)
        + '\n'
    )
    out_path.write_text(text, encoding='utf-8')
    print('Wrote', out_path, 'as_of', as_of, flush=True)


if __name__ == '__main__':
    main()
